---
engines:
  csslint:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- test/
<<<<<<< HEAD
- "*/migrations/"
=======
- "*/migrations/"
>>>>>>> 50a000f4b138f5659beb073f456ea54792a53784
